#include "adc_channels.h"

/* Default / Vref channel indices */
const uint8_t ANALOG_DEFAULT_INPUTS[MAX_ADC_CHANNELS] = {2,2,1}; // !!! ADC1 == CH3, ADC3 == CH1
const uint8_t ANALOG_VREF_INPUTS[MAX_ADC_CHANNELS]    = {6,0,0};

/* ADC1 */
const uint16_t ANALOG_PIN_ADC1[ADC1_NUM_CHANNELS] = {GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_0,0,0};
GPIO_TypeDef * const ANALOG_GPIO_ADC1[ADC1_NUM_CHANNELS] = {GPIOB,GPIOC,GPIOC,GPIOA,GPIOA,0,0};
const uint32_t ANALOG_CHANNEL_ADC1[ADC1_NUM_CHANNELS] = {ADC_CHANNEL_8,ADC_CHANNEL_11,ADC_CHANNEL_10,ADC_CHANNEL_1,ADC_CHANNEL_0,ADC_CHANNEL_16,ADC_CHANNEL_17};
const char* const ANALOG_CHANN_ADC1_NAME[ADC1_NUM_CHANNELS] = {"A3","A4","A5","A1","A0","Temp","Vref"};

/* ADC2 */
const uint16_t ANALOG_PIN_ADC2[ADC2_NUM_CHANNELS] = {GPIO_PIN_1,GPIO_PIN_0,GPIO_PIN_0,0};
GPIO_TypeDef * const ANALOG_GPIO_ADC2[ADC2_NUM_CHANNELS] = {GPIOC,GPIOC,GPIOA,0};
const uint32_t ANALOG_CHANNEL_ADC2[ADC2_NUM_CHANNELS] = {ADC_CHANNEL_11,ADC_CHANNEL_10,ADC_CHANNEL_8,ADC_CHANNEL_17};
const char* const ANALOG_CHANN_ADC2_NAME[ADC2_NUM_CHANNELS] = {"A4","A5","A3","Vref"};

/* ADC3 */
const uint16_t ANALOG_PIN_ADC3[ADC3_NUM_CHANNELS] = {GPIO_PIN_0,GPIO_PIN_1,GPIO_PIN_0,GPIO_PIN_1,0};
GPIO_TypeDef * const ANALOG_GPIO_ADC3[ADC3_NUM_CHANNELS] = {GPIOC,GPIOC,GPIOA,GPIOA,0};
const uint32_t ANALOG_CHANNEL_ADC3[ADC3_NUM_CHANNELS] = {ADC_CHANNEL_10,ADC_CHANNEL_11,ADC_CHANNEL_0,ADC_CHANNEL_1,ADC_CHANNEL_17};
const char* const ANALOG_CHANN_ADC3_NAME[ADC3_NUM_CHANNELS] = {"A5","A4","A0","A1","Vref"};

/* ADC4 */
const uint16_t ANALOG_PIN_ADC4[ADC4_NUM_CHANNELS] = {0};
GPIO_TypeDef * const ANALOG_GPIO_ADC4[ADC4_NUM_CHANNELS] = {0};
const uint32_t ANALOG_CHANNEL_ADC4[ADC4_NUM_CHANNELS] = {0};
const char* const ANALOG_CHANN_ADC4_NAME[ADC4_NUM_CHANNELS] = {"NA"};

/* Counts */
const uint8_t NUM_OF_ANALOG_INPUTS[MAX_ADC_CHANNELS] = {ADC1_NUM_CHANNELS,ADC2_NUM_CHANNELS,ADC3_NUM_CHANNELS};
